name:                plis-haskell
version:             0.1.0
github:              "axelbojrup/plis-haskell"
license:             BSD3
author:              "Axel Bojrup"
maintainer:          "bojrupo@hotmail.com"
copyright:           "Copyright (c) 2019 plis-team"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            serverless-haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/axelbojrup/plis-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson

library:
  source-dirs: src

executables:
  plis-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plis-haskell

tests:
  plis-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plis-haskell
